apiVersion: v2
appVersion: "1.0"
description: A Helm chart for RD Location Ref Data Load App
name: rd-location-ref-data-load
home: https://github.com/hmcts/rd-location-ref-data-load
version: 0.0.16
maintainers:
  - name: Reference Data Team
dependencies:
  - name: job
    version: 0.7.3
    repository: '@hmctspublic'
  - name: blobstorage
    version: 0.2.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: blobstorage.enabled
  - name: postgresql
    version: ~8.9.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
