aggregation-strategy-completion-size: 100
aggregation-strategy-timeout: 2000
archival-route: direct:LrdArchival
archival-path: azure-storage-blob://${azure.storage.account-name}/lrd-ref-data-archive
active-blob-path: azure-storage-blob://${azure.storage.account-name}/lrd-ref-data
archival-file-names: OrgServiceCCDMapping.csv, BuildingLocation.csv, CourtVenue.csv
archival-cred: credentials=#credsreg&operation=uploadBlockBlob
archival-date-format: dd-MM-yyyy--HH-mm
file-read-time-out: 180000
batchjob-name: LocationRefDataLoad
scheduler-audit-select: SELECT COUNT(*) FROM dataload_schedular_audit where DATE(scheduler_start_time) = current_date
invalid-exception-sql: INSERT INTO dataload_exception_records(table_name,scheduler_start_time,scheduler_name,error_description,updated_timestamp) VALUES(?, ?, ?, ?, ?)
invalid-jsr-sql: INSERT INTO dataload_exception_records(table_name,scheduler_start_time,scheduler_name,key,field_in_error,error_description,updated_timestamp, row_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?)
#jsr-threshold-limit: 100
scheduler-insert-sql: INSERT INTO dataload_schedular_audit (scheduler_name,file_name, scheduler_start_time,scheduler_end_time,status) VALUES(?,?,?,?,?)
audit-enable: true
logging-component-name: RD_Location_Ref_Data
component:
  name: Location Reference Data
region-query: SELECT region_id FROM region
cluster-query: SELECT cluster_id FROM cluster
epimms-id-query: SELECT epimms_id FROM building_location
court-type-id-query: SELECT court_type_id FROM court_type
