server:
  port: 8099

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: location reference data load
  main:
    allow-circular-references: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        default_schema: locrefdata
        jdbc:
          lob:
            non_contextual_creation: true
  batch:
    jdbc:
     initialize-schema: always
      #run spring batch job manually as need to validate idempotent condition in code
      #rather than giving control to spring
    job:
      enabled: false
#  jackson.date-format: yyyy-MM-dd
  flyway:
    enabled: false
    locations: classpath:db/migration
    schemas: locrefdata
  config:
    import: "optional:configtree:/mnt/secrets/rd/"
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5458}/${POSTGRES_NAME:locrefdata}?currentSchema=locrefdata
    username: ${POSTGRES_USERNAME:locrefdata}
    password: ${POSTGRES_PASSWORD:locrefdata}
    properties:
      charSet: UTF-8
    hikari:
      max-lifetime: 600000
      maximumPoolSize: ${HIKARI_MAX_POOL_SIZE:50}
      idle-timeout: 30000
      minimum-idle: 1

  profiles:
    include:
      - lrd-router
      - lib
      - camel-routes-common
      - lrd-building-location-router
      - lrd-court-venue-router
mail:
  enabled: false

zero-byte-characters: >
  \u200B,
   
